[workspace]
members = [
    "deskdrop-core",
    "deskdrop-cli",
    "platforms/linux",
]
resolver = "2"

[workspace.package]
version = "1.2.4"
edition = "2021"
authors = ["Deskdrop Contributors"]
license = "AGPL-3.0-only"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev.package.sha2]
opt-level = 3
[profile.dev.package.crypto-common]
opt-level = 3
[profile.dev.package.block-buffer]
opt-level = 3
[profile.dev.package.digest]
opt-level = 3
[profile.dev.package.aes-gcm]
opt-level = 3
[profile.dev.package.aes]
opt-level = 3
[profile.dev.package.ghash]
opt-level = 3
[profile.dev.package.cipher]
opt-level = 3
[profile.dev.package.x25519-dalek]
opt-level = 3
[profile.dev.package.curve25519-dalek]
opt-level = 3
[profile.dev.package.lz4_flex]
opt-level = 3
